name: Test project

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Get Ninja
      run: |
        sudo apt install ninja-build
    - name: Get Python3
      run: |
        sudo apt install python3
        sudo apt install python3-pip
        pip3 install networkx
    - name: Get Lemon
      run: |
        bash prepare.sh
    - name: Get MPI
      run: |
        sudo apt install mpich
    - name: Get CGAL
      run: |
        sudo apt-get install libcgal-dev
    - name: Build project
      run: |
        mkdir build
        cd build
        cmake .. -GNinja
        ninja
    - name: Run GoogleTest
      run: |
        cd build/
        ./gd_test
